# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20170921_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='procedure',
            field=models.TextField(default=''),
        ),
    ]
