# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.5 on 2017-09-21 06:25
=======
# Generated by Django 1.11.5 on 2017-09-21 12:09
>>>>>>> 94f03e72aa64dca7e9a93020825c8b8e1becc14a
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20170921_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='procedure',
            field=models.TextField(default=''),
        ),
    ]
